-- MySQL Script generated by MySQL Workbench
-- 07/11/15 19:30:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `salt` VARCHAR(255) NOT NULL COMMENT '',
  `roles` VARCHAR(255) NOT NULL COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `time_created` INT(11) UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  `username` VARCHAR(100) NULL COMMENT '',
  `isEnabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  `confirmationToken` VARCHAR(100) NULL COMMENT '',
  `timePasswordResetRequested` INT(11) UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gn` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupe` (
  `id` INT NOT NULL COMMENT '',
  `nom` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  `code` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archetype` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  `image` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`age`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`age` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sexe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sexe` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personnage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personnage` (
  `id` INT NOT NULL COMMENT '',
  `nom` VARCHAR(100) NOT NULL COMMENT '',
  `surnom` VARCHAR(100) NULL COMMENT '',
  `intrigue` TINYINT(1) NULL COMMENT '',
  `groupe_id` INT NOT NULL COMMENT '',
  `users_id` INT UNSIGNED NOT NULL COMMENT '',
  `archetype_id` INT NOT NULL COMMENT '',
  `age_id` INT NOT NULL COMMENT '',
  `sexe_id` INT NOT NULL COMMENT '',
  `renomme` INT NULL COMMENT '',
  `photo` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_personnage_groupe1_idx` (`groupe_id` ASC)  COMMENT '',
  INDEX `fk_personnage_users1_idx` (`users_id` ASC)  COMMENT '',
  INDEX `fk_personnage_archetype1_idx` (`archetype_id` ASC)  COMMENT '',
  INDEX `fk_personnage_age1_idx` (`age_id` ASC)  COMMENT '',
  INDEX `fk_personnage_sexe1_idx` (`sexe_id` ASC)  COMMENT '',
  CONSTRAINT `fk_personnage_groupe1`
    FOREIGN KEY (`groupe_id`)
    REFERENCES `mydb`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnage_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnage_archetype1`
    FOREIGN KEY (`archetype_id`)
    REFERENCES `mydb`.`archetype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnage_age1`
    FOREIGN KEY (`age_id`)
    REFERENCES `mydb`.`age` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnage_sexe1`
    FOREIGN KEY (`sexe_id`)
    REFERENCES `mydb`.`sexe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(100) NOT NULL COMMENT '',
  `description` VARCHAR(255) NULL COMMENT '',
  `impot` INT NULL COMMENT '',
  `richesse` INT NULL COMMENT '',
  `histoire` LONGTEXT NULL COMMENT '',
  `capitale` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chronologie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chronologie` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  `description` MEDIUMTEXT NOT NULL COMMENT '',
  `pays_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_chronologie_pays1_idx` (`pays_id` ASC)  COMMENT '',
  CONSTRAINT `fk_chronologie_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `mydb`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personnage_gn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personnage_gn` (
  `personnage_id` INT NOT NULL COMMENT '',
  `gn_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`personnage_id`, `gn_id`)  COMMENT '',
  INDEX `fk_personnage_gn_gn1_idx` (`gn_id` ASC)  COMMENT '',
  CONSTRAINT `fk_personnage_gn_personnage`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnage_gn_gn1`
    FOREIGN KEY (`gn_id`)
    REFERENCES `mydb`.`gn` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ressource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ressource` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(100) NOT NULL COMMENT '',
  `rarete` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pays_importation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays_importation` (
  `pays_id` INT NOT NULL COMMENT '',
  `ressource_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pays_id`, `ressource_id`)  COMMENT '',
  INDEX `fk_pays_importation_pays1_idx` (`pays_id` ASC)  COMMENT '',
  INDEX `fk_pays_importation_ressource1_idx` (`ressource_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pays_importation_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `mydb`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pays_importation_ressource1`
    FOREIGN KEY (`ressource_id`)
    REFERENCES `mydb`.`ressource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pays_exportation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays_exportation` (
  `pays_id` INT NOT NULL COMMENT '',
  `ressource_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pays_id`, `ressource_id`)  COMMENT '',
  INDEX `fk_pays_exportation_pays1_idx` (`pays_id` ASC)  COMMENT '',
  INDEX `fk_pays_exportation_ressource1_idx` (`ressource_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pays_exportation_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `mydb`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pays_exportation_ressource1`
    FOREIGN KEY (`ressource_id`)
    REFERENCES `mydb`.`ressource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(100) NULL COMMENT '',
  `dirigeant` VARCHAR(100) NULL COMMENT '',
  `capitale` VARCHAR(100) NULL COMMENT '',
  `protection` INT NULL COMMENT '',
  `puissance` INT NULL COMMENT '',
  `puissance_max` INT NULL COMMENT '',
  `impot` INT NULL COMMENT '',
  `richesse` INT NULL COMMENT '',
  `groupe_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_fief_groupe1_idx` (`groupe_id` ASC)  COMMENT '',
  CONSTRAINT `fk_fief_groupe1`
    FOREIGN KEY (`groupe_id`)
    REFERENCES `mydb`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pays_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays_region` (
  `pays_id` INT NOT NULL COMMENT '',
  `region_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pays_id`, `region_id`)  COMMENT '',
  INDEX `fk_pays_fief_fief1_idx` (`region_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pays_fief_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `mydb`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pays_fief_fief1`
    FOREIGN KEY (`region_id`)
    REFERENCES `mydb`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupe_archetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupe_archetype` (
  `groupe_id` INT NOT NULL COMMENT '',
  `archetype_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`groupe_id`, `archetype_id`)  COMMENT '',
  INDEX `fk_groupe_archetype_archetype1_idx` (`archetype_id` ASC)  COMMENT '',
  CONSTRAINT `fk_groupe_archetype_groupe1`
    FOREIGN KEY (`groupe_id`)
    REFERENCES `mydb`.`groupe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groupe_archetype_archetype1`
    FOREIGN KEY (`archetype_id`)
    REFERENCES `mydb`.`archetype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`langue` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personnage_langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personnage_langue` (
  `personnage_id` INT NOT NULL COMMENT '',
  `langue_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`personnage_id`, `langue_id`)  COMMENT '',
  INDEX `fk_personnage_langue_langue1_idx` (`langue_id` ASC)  COMMENT '',
  CONSTRAINT `fk_personnage_langue_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personnage_langue_langue1`
    FOREIGN KEY (`langue_id`)
    REFERENCES `mydb`.`langue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pays_langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pays_langue` (
  `pays_id` INT NOT NULL COMMENT '',
  `langue_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`pays_id`, `langue_id`)  COMMENT '',
  INDEX `fk_pays_langue_langue1_idx` (`langue_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pays_langue_pays1`
    FOREIGN KEY (`pays_id`)
    REFERENCES `mydb`.`pays` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pays_langue_langue1`
    FOREIGN KEY (`langue_id`)
    REFERENCES `mydb`.`langue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guilde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guilde` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confrerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confrerie` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`culte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`culte` (
  `id` INT NOT NULL COMMENT '',
  `label` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(450) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guilde_postulant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guilde_postulant` (
  `guilde_id` INT NOT NULL COMMENT '',
  `personnage_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`guilde_id`, `personnage_id`)  COMMENT '',
  INDEX `fk_guilde_postulant_personnage1_idx` (`personnage_id` ASC)  COMMENT '',
  CONSTRAINT `fk_guilde_postulant_guilde1`
    FOREIGN KEY (`guilde_id`)
    REFERENCES `mydb`.`guilde` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guilde_postulant_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confrerie_postulant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confrerie_postulant` (
  `confrerie_id` INT NOT NULL COMMENT '',
  `personnage_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`confrerie_id`, `personnage_id`)  COMMENT '',
  INDEX `fk_confrerie_postulant_personnage1_idx` (`personnage_id` ASC)  COMMENT '',
  CONSTRAINT `fk_confrerie_postulant_confrerie1`
    FOREIGN KEY (`confrerie_id`)
    REFERENCES `mydb`.`confrerie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_confrerie_postulant_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`culte_postulant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`culte_postulant` (
  `culte_id` INT NOT NULL COMMENT '',
  `personnage_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`culte_id`, `personnage_id`)  COMMENT '',
  INDEX `fk_culte_postulant_personnage1_idx` (`personnage_id` ASC)  COMMENT '',
  CONSTRAINT `fk_culte_postulant_culte1`
    FOREIGN KEY (`culte_id`)
    REFERENCES `mydb`.`culte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_culte_postulant_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guilde_personnage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guilde_personnage` (
  `guilde_id` INT NOT NULL COMMENT '',
  `personnage_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`guilde_id`, `personnage_id`)  COMMENT '',
  INDEX `fk_guilde_personnage_personnage1_idx` (`personnage_id` ASC)  COMMENT '',
  CONSTRAINT `fk_guilde_personnage_guilde1`
    FOREIGN KEY (`guilde_id`)
    REFERENCES `mydb`.`guilde` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guilde_personnage_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`confrerie_personnage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confrerie_personnage` (
  `confrerie_id` INT NOT NULL COMMENT '',
  `personnage_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`confrerie_id`, `personnage_id`)  COMMENT '',
  INDEX `fk_confrerie_personnage_personnage1_idx` (`personnage_id` ASC)  COMMENT '',
  CONSTRAINT `fk_confrerie_personnage_confrerie1`
    FOREIGN KEY (`confrerie_id`)
    REFERENCES `mydb`.`confrerie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_confrerie_personnage_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`culte_personnage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`culte_personnage` (
  `culte_id` INT NOT NULL COMMENT '',
  `personnage_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`culte_id`, `personnage_id`)  COMMENT '',
  INDEX `fk_culte_personnage_personnage1_idx` (`personnage_id` ASC)  COMMENT '',
  CONSTRAINT `fk_culte_personnage_culte1`
    FOREIGN KEY (`culte_id`)
    REFERENCES `mydb`.`culte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_culte_personnage_personnage1`
    FOREIGN KEY (`personnage_id`)
    REFERENCES `mydb`.`personnage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
