<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-07-02 20:39:27.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseAge;

/**
 * LarpManager\Entities\Age
 *
 * @Entity()
 */
class Age extends BaseAge
{
	public function __toString()
	{
		return $this->getLabel();
	}
}