<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-07-07 22:08:08.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * LarpManager\Entities\Objet
 *
 * @Entity()
 * @Table(name="objet", indexes={@Index(name="fk_objet_localisation1_idx", columns={"localisation_id"}), @Index(name="fk_objet_etat1_idx", columns={"etat_id"}), @Index(name="fk_objet_possesseur1_idx", columns={"possesseur_id"}), @Index(name="fk_objet_users1_idx", columns={"responsable_id"})})
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"base":"BaseObjet", "extended":"Objet"})
 */
class BaseObjet
{
    /**
     * @Id
     * @Column(type="integer")
     */
    protected $id;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $code;

    /**
     * @Column(type="string", length=100, nullable=true)
     */
    protected $photo;

    /**
     * @Column(type="string", length=100, nullable=true)
     */
    protected $nom;

    /**
     * @Column(type="string", length=450, nullable=true)
     */
    protected $description;

    /**
     * @Column(type="integer")
     */
    protected $localisation_id;

    /**
     * @Column(type="integer")
     */
    protected $etat_id;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $taille;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $poid;

    /**
     * @Column(type="string", length=100, nullable=true)
     */
    protected $couleur;

    /**
     * @Column(type="integer")
     */
    protected $possesseur_id;

    /**
     * @Column(type="integer", options={"unsigned":true})
     */
    protected $responsable_id;

    /**
     * @Column(type="boolean", nullable=true)
     */
    protected $multiple;

    /**
     * @Column(type="float", nullable=true)
     */
    protected $cout;

    /**
     * @Column(type="float", nullable=true)
     */
    protected $budget;

    /**
     * @Column(type="boolean", nullable=true)
     */
    protected $investissement;

    /**
     * @ManyToOne(targetEntity="Localisation", inversedBy="objets")
     * @JoinColumn(name="localisation_id", referencedColumnName="id")
     */
    protected $localisation;

    /**
     * @ManyToOne(targetEntity="Etat", inversedBy="objets")
     * @JoinColumn(name="etat_id", referencedColumnName="id")
     */
    protected $etat;

    /**
     * @ManyToOne(targetEntity="Possesseur", inversedBy="objets")
     * @JoinColumn(name="possesseur_id", referencedColumnName="id")
     */
    protected $possesseur;

    /**
     * @ManyToOne(targetEntity="Users", inversedBy="objets")
     * @JoinColumn(name="responsable_id", referencedColumnName="id")
     */
    protected $users;

    /**
     * @ManyToMany(targetEntity="Tag", inversedBy="objets")
     * @JoinTable(name="objet_tag",
     *     joinColumns={@JoinColumn(name="objet_id", referencedColumnName="id")},
     *     inverseJoinColumns={@JoinColumn(name="tag_id", referencedColumnName="id")}
     * )
     */
    protected $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \LarpManager\Entities\Objet
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of code.
     *
     * @param integer $code
     * @return \LarpManager\Entities\Objet
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get the value of code.
     *
     * @return integer
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set the value of photo.
     *
     * @param string $photo
     * @return \LarpManager\Entities\Objet
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get the value of photo.
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set the value of nom.
     *
     * @param string $nom
     * @return \LarpManager\Entities\Objet
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get the value of nom.
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set the value of description.
     *
     * @param string $description
     * @return \LarpManager\Entities\Objet
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get the value of description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set the value of localisation_id.
     *
     * @param integer $localisation_id
     * @return \LarpManager\Entities\Objet
     */
    public function setLocalisationId($localisation_id)
    {
        $this->localisation_id = $localisation_id;

        return $this;
    }

    /**
     * Get the value of localisation_id.
     *
     * @return integer
     */
    public function getLocalisationId()
    {
        return $this->localisation_id;
    }

    /**
     * Set the value of etat_id.
     *
     * @param integer $etat_id
     * @return \LarpManager\Entities\Objet
     */
    public function setEtatId($etat_id)
    {
        $this->etat_id = $etat_id;

        return $this;
    }

    /**
     * Get the value of etat_id.
     *
     * @return integer
     */
    public function getEtatId()
    {
        return $this->etat_id;
    }

    /**
     * Set the value of taille.
     *
     * @param integer $taille
     * @return \LarpManager\Entities\Objet
     */
    public function setTaille($taille)
    {
        $this->taille = $taille;

        return $this;
    }

    /**
     * Get the value of taille.
     *
     * @return integer
     */
    public function getTaille()
    {
        return $this->taille;
    }

    /**
     * Set the value of poid.
     *
     * @param integer $poid
     * @return \LarpManager\Entities\Objet
     */
    public function setPoid($poid)
    {
        $this->poid = $poid;

        return $this;
    }

    /**
     * Get the value of poid.
     *
     * @return integer
     */
    public function getPoid()
    {
        return $this->poid;
    }

    /**
     * Set the value of couleur.
     *
     * @param string $couleur
     * @return \LarpManager\Entities\Objet
     */
    public function setCouleur($couleur)
    {
        $this->couleur = $couleur;

        return $this;
    }

    /**
     * Get the value of couleur.
     *
     * @return string
     */
    public function getCouleur()
    {
        return $this->couleur;
    }

    /**
     * Set the value of possesseur_id.
     *
     * @param integer $possesseur_id
     * @return \LarpManager\Entities\Objet
     */
    public function setPossesseurId($possesseur_id)
    {
        $this->possesseur_id = $possesseur_id;

        return $this;
    }

    /**
     * Get the value of possesseur_id.
     *
     * @return integer
     */
    public function getPossesseurId()
    {
        return $this->possesseur_id;
    }

    /**
     * Set the value of responsable_id.
     *
     * @param integer $responsable_id
     * @return \LarpManager\Entities\Objet
     */
    public function setResponsableId($responsable_id)
    {
        $this->responsable_id = $responsable_id;

        return $this;
    }

    /**
     * Get the value of responsable_id.
     *
     * @return integer
     */
    public function getResponsableId()
    {
        return $this->responsable_id;
    }

    /**
     * Set the value of multiple.
     *
     * @param boolean $multiple
     * @return \LarpManager\Entities\Objet
     */
    public function setMultiple($multiple)
    {
        $this->multiple = $multiple;

        return $this;
    }

    /**
     * Get the value of multiple.
     *
     * @return boolean
     */
    public function getMultiple()
    {
        return $this->multiple;
    }

    /**
     * Set the value of cout.
     *
     * @param float $cout
     * @return \LarpManager\Entities\Objet
     */
    public function setCout($cout)
    {
        $this->cout = $cout;

        return $this;
    }

    /**
     * Get the value of cout.
     *
     * @return float
     */
    public function getCout()
    {
        return $this->cout;
    }

    /**
     * Set the value of budget.
     *
     * @param float $budget
     * @return \LarpManager\Entities\Objet
     */
    public function setBudget($budget)
    {
        $this->budget = $budget;

        return $this;
    }

    /**
     * Get the value of budget.
     *
     * @return float
     */
    public function getBudget()
    {
        return $this->budget;
    }

    /**
     * Set the value of investissement.
     *
     * @param boolean $investissement
     * @return \LarpManager\Entities\Objet
     */
    public function setInvestissement($investissement)
    {
        $this->investissement = $investissement;

        return $this;
    }

    /**
     * Get the value of investissement.
     *
     * @return boolean
     */
    public function getInvestissement()
    {
        return $this->investissement;
    }

    /**
     * Set Localisation entity (many to one).
     *
     * @param \LarpManager\Entities\Localisation $localisation
     * @return \LarpManager\Entities\Objet
     */
    public function setLocalisation(Localisation $localisation = null)
    {
        $this->localisation = $localisation;

        return $this;
    }

    /**
     * Get Localisation entity (many to one).
     *
     * @return \LarpManager\Entities\Localisation
     */
    public function getLocalisation()
    {
        return $this->localisation;
    }

    /**
     * Set Etat entity (many to one).
     *
     * @param \LarpManager\Entities\Etat $etat
     * @return \LarpManager\Entities\Objet
     */
    public function setEtat(Etat $etat = null)
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * Get Etat entity (many to one).
     *
     * @return \LarpManager\Entities\Etat
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * Set Possesseur entity (many to one).
     *
     * @param \LarpManager\Entities\Possesseur $possesseur
     * @return \LarpManager\Entities\Objet
     */
    public function setPossesseur(Possesseur $possesseur = null)
    {
        $this->possesseur = $possesseur;

        return $this;
    }

    /**
     * Get Possesseur entity (many to one).
     *
     * @return \LarpManager\Entities\Possesseur
     */
    public function getPossesseur()
    {
        return $this->possesseur;
    }

    /**
     * Set Users entity (many to one).
     *
     * @param \LarpManager\Entities\Users $users
     * @return \LarpManager\Entities\Objet
     */
    public function setUsers(Users $users = null)
    {
        $this->users = $users;

        return $this;
    }

    /**
     * Get Users entity (many to one).
     *
     * @return \LarpManager\Entities\Users
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * Add Tag entity to collection.
     *
     * @param \LarpManager\Entities\Tag $tag
     * @return \LarpManager\Entities\Objet
     */
    public function addTag(Tag $tag)
    {
        $tag->addObjet($this);
        $this->tags[] = $tag;

        return $this;
    }

    /**
     * Remove Tag entity from collection.
     *
     * @param \LarpManager\Entities\Tag $tag
     * @return \LarpManager\Entities\Objet
     */
    public function removeTag(Tag $tag)
    {
        $tag->removeObjet($this);
        $this->tags->removeElement($tag);

        return $this;
    }

    /**
     * Get Tag entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTags()
    {
        return $this->tags;
    }

    public function __sleep()
    {
        return array('id', 'code', 'photo', 'nom', 'description', 'localisation_id', 'etat_id', 'taille', 'poid', 'couleur', 'possesseur_id', 'responsable_id', 'multiple', 'cout', 'budget', 'investissement');
    }
}