<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-08-25 21:04:50.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * LarpManager\Entities\Joueur
 *
 * @Entity()
 * @Table(name="joueur", indexes={@Index(name="fk_joueur_personnage1_idx", columns={"personnage_id"})})
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"base":"BaseJoueur", "extended":"Joueur"})
 */
class BaseJoueur
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="integer", nullable=true)
     */
    protected $xp;

    /**
     * @OneToOne(targetEntity="User", mappedBy="joueur")
     */
    protected $user;

    /**
     * @OneToOne(targetEntity="Personnage", inversedBy="joueur")
     * @JoinColumn(name="personnage_id", referencedColumnName="id")
     */
    protected $personnage;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \LarpManager\Entities\Joueur
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of xp.
     *
     * @param integer $xp
     * @return \LarpManager\Entities\Joueur
     */
    public function setXp($xp)
    {
        $this->xp = $xp;

        return $this;
    }

    /**
     * Get the value of xp.
     *
     * @return integer
     */
    public function getXp()
    {
        return $this->xp;
    }

    /**
     * Set User entity (one to one).
     *
     * @param \LarpManager\Entities\User $user
     * @return \LarpManager\Entities\Joueur
     */
    public function setUser(User $user = null)
    {
        $user->setJoueur($this);
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (one to one).
     *
     * @return \LarpManager\Entities\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set Personnage entity (one to one).
     *
     * @param \LarpManager\Entities\Personnage $personnage
     * @return \LarpManager\Entities\Joueur
     */
    public function setPersonnage(Personnage $personnage)
    {
        $this->personnage = $personnage;

        return $this;
    }

    /**
     * Get Personnage entity (one to one).
     *
     * @return \LarpManager\Entities\Personnage
     */
    public function getPersonnage()
    {
        return $this->personnage;
    }

    public function __sleep()
    {
        return array('id', 'xp', 'personnage_id');
    }
}