<?php

/**
 * Generated by Kevin F.
 */

namespace LarpManager\Entities;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * LarpManager\Entities\GroupeGnOrdre
 *
 * @Entity()
 * @Table(name="groupe_gn_ordre")
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"base":"BaseGroupeGnOrdre", "extended":"GroupeGnOrdre"})
 */
class BaseGroupeGnOrdre
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(name="`ordre`", type="string")
     */
    protected $ordre;

    /**
     * @Column(name="`extra`", type="string")
     */
    protected $extra;

    /**
     * @ManyToOne(targetEntity="GroupeGn", inversedBy="groupeGnOrdre")
     * @JoinColumn(name="groupe_gn_id", referencedColumnName="id", nullable=false)
     */
    protected $groupe_gn;

    /**
     * @ManyToOne(targetEntity="Territoire", inversedBy="groupeGnOrdre")
     * @JoinColumn(name="cible_id", referencedColumnName="id")
     */
    protected $cible;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \LarpManager\Entities\GroupeGnOrdre
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of ordre.
     *
     * @param boolean $ordre
     * @return \LarpManager\Entities\GroupeGnOrdre
     */
    public function setOrdre($ordre)
    {
        $this->ordre = $ordre;

        return $this;
    }

    /**
     * Get the value of ordre.
     *
     * @return boolean
     */
    public function getOrdre()
    {
        return $this->ordre;
    }

    /**
     * Set the value of extra.
     *
     * @param boolean $extra
     * @return \LarpManager\Entities\GroupeGnOrdre
     */
    public function setExtra($extra)
    {
        $this->extra = $extra;

        return $this;
    }

    /**
     * Get the value of extra.
     *
     * @return boolean
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Set the value of cible.
     *
     * @param boolean $cible
     * @return \LarpManager\Entities\GroupeGnOrdre
     */

    public function setCible($cible)
    {
        $this->cible = $cible;

        return $this;
    }

    /**
     * Get Territoire entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCible()
    {
        return $this->cible;
    }

    /**
     * Set GroupeGn entity (many to one).
     *
     * @param \LarpManager\Entities\GroupeGn $groupeGn
     * @return \LarpManager\Entities\GroupeGnOrdre
     */
    public function setGroupeGN(GroupeGN $groupeGN)
    {
        $this->groupeGn = $groupeGn;

        return $this;
    }

    /**
     * Get GroupeGn entity (many to one).
     *
     * @return \LarpManager\Entities\GroupeGn
     */
    public function getGroupeGn()
    {
        return $this->groupeGn;
    }

    public function __sleep()
    {
        return array('id', 'ordre', 'groupe_gn_id', 'cible_id');
    }
}