<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotation) on 2019-11-07 10:18:54.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * LarpManager\Entities\GroupeLangue
 *
 * @Entity()
 * @Table(name="groupe_langue")
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"base":"BaseGroupeLangue", "extended":"GroupeLangue"})
 */
class BaseGroupeLangue
{
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Column(type="string", length=100)
     */
    protected $label;

    /**
     * @Column(type="string", length=45)
     */
    protected $couleur;

    /**
     * @OneToMany(targetEntity="Langue", mappedBy="groupeLangue")
     * @JoinColumn(name="id", referencedColumnName="groupe_langue_id", nullable=false)
     */
    protected $langues;

    public function __construct()
    {
        $this->langues = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \LarpManager\Entities\GroupeLangue
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of label.
     *
     * @param string $label
     * @return \LarpManager\Entities\GroupeLangue
     */
    public function setLabel($label)
    {
        $this->label = $label;

        return $this;
    }

    /**
     * Get the value of label.
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Set the value of couleur.
     *
     * @param string $couleur
     * @return \LarpManager\Entities\GroupeLangue
     */
    public function setCouleur($couleur)
    {
        $this->couleur = $couleur;

        return $this;
    }

    /**
     * Get the value of couleur.
     *
     * @return string
     */
    public function getCouleur()
    {
        return $this->couleur;
    }

    /**
     * Add Langue entity to collection (one to many).
     *
     * @param \LarpManager\Entities\Langue $langue
     * @return \LarpManager\Entities\GroupeLangue
     */
    public function addLangue(Langue $langue)
    {
        $this->langues[] = $langue;

        return $this;
    }

    /**
     * Remove Langue entity from collection (one to many).
     *
     * @param \LarpManager\Entities\Langue $langue
     * @return \LarpManager\Entities\GroupeLangue
     */
    public function removeLangue(Langue $langue)
    {
        $this->langues->removeElement($langue);

        return $this;
    }

    /**
     * Get Langue entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLangues()
    {
        return $this->langues;
    }

    public function __sleep()
    {
        return array('id', 'label', 'couleur');
    }
}