<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-06-30 20:35:19.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseChronologie;

/**
 * LarpManager\Entities\Chronologie
 *
 * @Entity(repositoryClass="LarpManager\Repository\ChronologieRepository")
 */
class Chronologie extends BaseChronologie implements \JsonSerializable
{
	/**
	 * Serializer
	 */
	public function jsonSerialize() {
		return array(
			'year' => $this->getYear(),
			'month' => $this->getMonth(),
			'day' => $this->getDay(),
			'description' => $this->getDescription(),
			'visibilite' => $this->getVisibilite(),
			'territoire_id' => ($this->getTerritoire() ) ? $this->getTerritoire()->getId() : '',
		);
	}
	
	/**
	 * Unserializer
	 * 
	 * @param unknown $payload
	 */
	public function jsonUnserialize($payload) {
		$this->setYear($payload->year);
		$this->setMonth($payload->month);
		$this->setDay($payload->day);
		$this->setDescription($payload->description);
		$this->setVisibilite($payload->visibilite);
	}
}