<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-08-15 13:14:22.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseCompetenceNiveau;

/**
 * LarpManager\Entities\CompetenceNiveau
 *
 * @Entity()
 */
class CompetenceNiveau extends BaseCompetenceNiveau
{
	
	public function __toString()
	{
		return $this->getLabel();
	}
	
	public function getNiveau()
	{
		$niveau = parent::getNiveau();
		if ( $niveau )
		{
			return $niveau->getNiveau();
		}	
		else 
		{
			return null;
		}
	}
	
	public function getCoutNormal()
	{
		$niveau = parent::getNiveau();
		if ( $niveau )
		{
			return $niveau->getCout();
		}
		return null;
	}
	
	public function getCoutFavori()
	{
		$niveau = parent::getNiveau();
		if ( $niveau )
		{
			return $niveau->getCoutFavori();
		}
		return null;		
	}
	
	public function getCoutMeconnu()
	{
		$niveau = parent::getNiveau();
		if ( $niveau )
		{
			return $niveau->getMeconnu();
		}
		return null;
	}
	
	public function getLabel()
	{
		$niveau = parent::getNiveau();
		
		if ( $niveau )
		{
			return $niveau->getLabel();
		}
		else
		{
			return null;
		}
	}
}