<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-08-05 07:22:37.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseDebriefing;

/**
 * LarpManager\Entities\Debriefing
 *
 * @Entity()
 */
class Debriefing extends BaseDebriefing
{
}