<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-12-02 09:37:51.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseFormulaire;

/**
 * LarpManager\Entities\Formulaire
 *
 * @Entity()
 */
class Formulaire extends BaseFormulaire
{
}