<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-08-18 10:24:14.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseGenre;

/**
 * LarpManager\Entities\Genre
 *
 * @Entity()
 */
class Genre extends BaseGenre
{
}