<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-05-13 15:19:57.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseIntrigueHasGroupeSecondaire;

/**
 * LarpManager\Entities\IntrigueHasGroupeSecondaire
 *
 * @Entity()
 */
class IntrigueHasGroupeSecondaire extends BaseIntrigueHasGroupeSecondaire
{
}