<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-09-01 11:12:41.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseJoueurGn;

/**
 * LarpManager\Entities\JoueurGn
 *
 * @Entity()
 */
class JoueurGn extends BaseJoueurGn
{
}