<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-09-21 09:47:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseMonnaie;

/**
 * LarpManager\Entities\Monnaie
 *
 * @Entity()
 */
class Monnaie extends BaseMonnaie
{
}