<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-07-15 11:28:41.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseObjetPhoto;

/**
 * LarpManager\Entities\ObjetPhoto
 *
 * @Entity()
 */
class ObjetPhoto extends BaseObjetPhoto
{
}