<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-06-30 20:35:19.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BasePays;

/**
 * LarpManager\Entities\Pays
 *
 * @Entity()
 */
class Pays extends BasePays
{
	/**
	 * Permet de définir la date de création
	 */
	public function __construct()
	{
		$this->setCreationDate(new \DateTime('NOW'));
		$this->setUpdateDate(new \DateTime('NOW'));
		parent::__construct();
	}
	
	/**
	 * Helper pour récupérer l'utilisateur qui a créé le pays
	 */
	public function getCreator()
	{
		$creator = $this->getUser();
		
		return $creator;
	}
	
	/**
	 * Helper pour définir l'utilisateur qui a créé le pays 
	 * @param User $user
	 */
	public function setCreator($user)
	{
		return $this->setUser($user);
	}
}