<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-01-12 19:49:20.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BasePersonnagesReligions;

/**
 * LarpManager\Entities\PersonnagesReligions
 *
 * @Entity()
 */
class PersonnagesReligions extends BasePersonnagesReligions
{
}