<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-06-30 20:35:19.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BasePersonnage;

/**
 * LarpManager\Entities\Personnage
 *
 * @Entity()
 */
class Personnage extends BasePersonnage
{
	/**
	 * Ajoute une competence dans la liste des competences d'un personnage
	 * @param Competence $competence
	 * @param Niveau $niveau
	 */
	public function addCompetence(Competence $competence, Niveau $niveau)
	{
		$personnageCompetence = new PersonnageCompetence();
		$personnageCompetence->setNiveau($niveau);
		$personnageCompetence->setCompetence($competence);
		$personnageCompetence->setPersonnage($this);
		$this->addPersonnageCompetence($personnageCompetence);
	}
}