<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-12-22 15:58:44.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BasePersonnageSecondaireCompetence;

/**
 * LarpManager\Entities\PersonnageSecondaireCompetence
 *
 * @Entity()
 */
class PersonnageSecondaireCompetence extends BasePersonnageSecondaireCompetence
{
}