<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-07-25 20:41:16.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BasePhoto;

/**
 * LarpManager\Entities\Photo
 *
 * @Entity()
 */
class Photo extends BasePhoto
{
	/**
	 * @Assert\File(maxSize="6000000")
	 */
	public $file;
		
	/**
	 * Upload file on database
	 */
	public function upload()
	{
		// la propriété « file » peut être vide si le champ n'est pas requis
		if (null === $this->file) {
			return;
		}
			
		// create a unique filename
		$date = new \Datetime('NOW');
		$hash = hash('sha1',$this->file->getClientOriginalName().$date->format('Y-m-d H:i:s'));
		$hash .= '.'.$this->file->guessExtension();
		
		
		$this->setExtension($this->file->guessExtension());
		$stream = fopen($this->file->getRealPath(),'rb');
		$this->setData(stream_get_contents($stream));
		
		$this->setCreationDate($date);
		$this->setName($this->file->getClientOriginalName());
		$this->setRealName($hash);
	
		// « nettoie » la propriété « file » comme vous n'en aurez plus besoin
		$this->file = null;
	}
}