<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-05-02 11:05:25.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseRenommeHistory;

/**
 * LarpManager\Entities\RenommeHistory
 *
 * @Entity()
 */
class RenommeHistory extends BaseRenommeHistory
{
	public function __construct()
	{
		$this->setDate(new \Datetime('NOW'));
	}
}