<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-07-02 10:16:21.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseSphere;

/**
 * LarpManager\Entities\Sphere
 *
 * @Entity()
 */
class Sphere extends BaseSphere
{
}