<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-06-17 12:44:22.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseTitre;

/**
 * LarpManager\Entities\Titre
 *
 * @Entity(repositoryClass="LarpManager\Repository\TitreRepository")
 */
class Titre extends BaseTitre
{
	public function __toString()
	{
		return $this->getLabel();
	}
}