<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2016-08-03 07:13:54.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace LarpManager\Entities;

use LarpManager\Entities\BaseToken;

/**
 * LarpManager\Entities\Token
 *
 * @Entity(repositoryClass="LarpManager\Repository\TokenRepository")
 */
class Token extends BaseToken
{
	/**
	 * Fourni la description sans les tags html de mise en forme
	 */
	public function getDescriptionRaw()
	{
		return html_entity_decode(strip_tags($this->getDescription()));
	}
	
	public function getExportValue()
	{
		return array(
			$this->getId(),
			$this->getLabel(),
			$this->getTag(),
			utf8_decode($this->getDescriptionRaw()),
		);
	}
}